[[pluings]]
repo = 'jackguo380/vim-lsp-cxx-highlight'
on_ft = [ 'c','cpp' ]
hook_source = '''
	call coc#config('languageserver', {
	\ 'ccls': {
		\ "command": "ccls",
		\ "rootPatterns": [".ccls", "compile_commands.json", ".git/", ".hg/"],
		\ "filetypes": ["c","cpp","objc","objcpp"],
		\ "initializationOptions": {
		\ "cache":{
			\ "directory": "/tmp/ccls"
		\ }
		\ }
		\ }
		\})
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go','gomod']
hook_add = '''
	nnoremap gcg :GoAuToComment<CR>
	let g:go_highlight_functions = 1
	let g:go_highlight_methods = 1
	let g:go_highlight_structs = 1
	let g:go_highlight_operators = 1
	let g:go_highlight_build_constraints = 1
'''
hook_source = '''
	call coc#config('languageserver', {
	\ 'golang': {
		\ "command": "gopls",
		\ "rootPatterns": ["go.mod"],
		\ "disableWorkspaceFolders": "true",
		\ "filetypes": ["go"]
		\ }
		\})
'''

[[plugins]]
repo = 'StanAngeloff/php.vim'
on_ft = 'php'
hook_source = '''
	"php lsp config
	call coc#config('languageserver', {
	\ 'intelephense': {
		\ "command": "intelephense",
		\ "args": ["--stdio"],
		\ "filetypes": ["php"],
		\ "initializationOptions": {
			\ "storagePath": "/tmp/intelephense"
		\ }
		\ }
		\})
'''

[[plugins]]
repo = 'vim-python/python-syntax'
on_ft = 'python'
Ghook_source = '''
	let g:python_highlight_all = 1
'''

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'vim-scripts/python_match.vim'
on_ft = 'python'

[[plugins]]
repo = 'raimon49/requirements.txt.vim'
on_ft = 'requirements'

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'tbastos/vim-lua'
on_ft = 'lua'
hook_source = '''
	call coc#config ('languageserver', {
			\'lua': {
				\ "cwd": "full path of lua-language-server directory", (not sure this one is really necessary)
				\ "command": "full path to lua-language-server executable",
				\ "args": ["-E", "-e", "LANG=en", "[full path of lua-language-server directory]/main.lua"],
				\ "filetypes": ["lua"],
				\ "rootPatterns": [".git/"]
				\}
				\})
'''

[[plugins]]
repo = 'sillybun/vim-repl'
